### ISSUE TITLE
Set up UI routes

### ISSUE THREAD

**Issue by jhand2** [info343-group1/group-project#7]

**Comment by alexsirr** [comment]
@jhand2 Just cloned the repo to check and see how things are going. Noticed that the ui-router is not cycling pages. Is that expected at this time or is it supposed to be working?

**Comment by JockFax32** [comment]
@alexsirr the UI router is working on my end. I noticed there the home page link was not working but it should be working after a quick fix. It should read  `<a class="grey-text text-lighten-3" ui-sref="home">Home</a>` on line 78 of `index.html`

**Comment by JockFax32** [comment]
If it reads `ui-sref="main"` I can do a quick push
